// column-config/ColumnConfigEvaluasiSales.ts
import { ApiSalesDetail } from "@/types/apiDataSalesDetail";

const columnConfigEvaluasiSales: Record<string, { label: string; key: keyof ApiSalesDetail; isNumber?: boolean }[]> = {
    perdivisi: [
        { label: "#", key: "index" },
        { label: "Div", key: "dtl_k_div" },
        { label: "Nama Div", key: "dtl_nama_div" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_no_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    perdepartement: [
        { label: "#", key: "index" },
        { label: "Div", key: "dtl_k_div" },
        { label: "Dept", key: "dtl_k_dept" },
        { label: "Nama Dept", key: "dtl_nama_dept" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_no_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    perkategori: [
        { label: "#", key: "index" },
        { label: "Div", key: "dtl_k_div" },
        { label: "Dept", key: "dtl_k_dept" },
        { label: "Kat", key: "dtl_k_katb" },
        { label: "Nama Kat", key: "dtl_nama_katb" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_no_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    perproduk: [
        { label: "#", key: "index" },
        { label: "D", key: "dtl_k_div" },
        { label: "Dp", key: "dtl_k_dept" },
        { label: "Kb", key: "dtl_k_katb" },
        { label: "Plu", key: "dtl_prdcd_ctn" },
        { label: "Deskripsi", key: "dtl_nama_barang" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_no_struk", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    "perproduk-tanggal": [
        { label: "#", key: "index" },
        { label: "D", key: "dtl_k_div" },
        { label: "Dp", key: "dtl_k_dept" },
        { label: "Kb", key: "dtl_k_katb" },
        { label: "Plu", key: "dtl_prdcd_ctn" },
        { label: "Deskripsi", key: "dtl_nama_barang" },
        { label: "Tanggal", key: "dtl_tanggal" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_no_struk", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    pertanggal: [
        { label: "#", key: "index" },
        { label: "Tanggal", key: "dtl_tanggal" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_no_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    perstruk: [
        { label: "#", key: "index" },
        { label: "Struk", key: "dtl_struk" },
        { label: "Station", key: "dtl_stat" },
        { label: "Kd Mem", key: "dtl_cusno" },
        { label: "Nama", key: "dtl_namamember" },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
        { label: "Jenis Mem", key: "dtl_flagmemberkhusus" }
    ],
    permember: [
        { label: "#", key: "index" },
        { label: "Outlet", key: "dtl_outlet" },
        { label: "Sub Out", key: "dtl_suboutlet" },
        { label: "Kd Mem", key: "dtl_cusno" },
        { label: "Nama", key: "dtl_namamember" },
        { label: "Struk", key: "dtl_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
        { label: "Awal_blnj", key: "dtl_tglmulai" },
        { label: "Akhir_blnj", key: "dtl_tglakhir" },
        { label: "Jenis Member", key: "dtl_flagmemberkhusus" },
    ],
    persupplier: [
        { label: "#", key: "index" },
        { label: "Kd Supp", key: "dtl_kodesupplier" },
        { label: "Nama Supp", key: "dtl_namasupplier" },
        { label: "Struk", key: "dtl_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    perkasir: [
        { label: "#", key: "index" },
        { label: "kasir", key: "dtl_kasir" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ],
    perbulan: [
        { label: "#", key: "index" },
        { label: "Bulan", key: "dtl_tanggal" },
        { label: "Member", key: "dtl_cusno", isNumber: true },
        { label: "Struk", key: "dtl_struk", isNumber: true },
        { label: "Produk", key: "dtl_prdcd_ctn", isNumber: true },
        { label: "Qty In Pcs", key: "dtl_qty_pcs", isNumber: true },
        { label: "Gross", key: "dtl_gross", isNumber: true },
        { label: "Netto", key: "dtl_netto", isNumber: true },
        { label: "Margin", key: "dtl_margin", isNumber: true },
        { label: "%", key: "dtl_margin_percent", isNumber: true },
    ]
};

export default columnConfigEvaluasiSales;
