export interface ApiDataKlik {
    obi_tglpb: string;
    obi_createdt: string;
    obi_maxdeliverytime: string;
    obi_itemorder: number;
    obi_realitem: number;
    obi_kdmember: string;
    obi_tipebayar: string;
    obi_shippingservice: string;
    trx: string;
    obi_key: string;
    status: string;
    obi_prdcd: string;
    obi_qty: number;
    obi_qtyorder: number;
    obi_qtyrealisasi: number;
    prd_deskripsipanjang: string;
    cus_namamember: string;
    obi_picker: string;
    sti_noawb: string;
    sti_tipeproses: string;
    obi_nopb: string;
};
